#! /bin/bash 
# -*- coding: UTF-8 -*-

#creation de la librairie dans laquelle on va mettre les fichiers compilés 
set TP_PATH "/home/romain/Documents/2022_2023/Phelma/Miniprojet_RISC_V"

vdel -lib  ${TP_PATH}/libs/lib_verilog -all

vlib ${TP_PATH}/libs/lib_verilog

vmap lib_verilog ${TP_PATH}/libs/lib_verilog 

#compilation des fichiers
vlog +acc -work  lib_verilog ${TP_PATH}/rtl/*.sv
vlog +acc -work  lib_verilog ${TP_PATH}/bench/*.sv
#vlog +acc -work lib_verilog ${TP_PATH}/rtl/3dff.sv
#vlog +acc -work lib_verilog ${TP_PATH}/bench/bench_regfile.sv

#lancer la simulation
vsim -voptargs=+acc lib_verilog.bench_riscv
#vsim -voptargs=+acc lib_verilog.bench_regfile
#add wave sim:/bench_regfile/*
#run 200

