#! /bin/bash 
# -*- coding: UTF-8 -*-

#creation de la librairie dans laquelle on va mettre les fichiers compilés 
set TP_PATH "/home/romain/Documents/2022_2023/Phelma/Miniprojet_RISC_V"
vdel -lib  ${TP_PATH}/libs/lib_verilog -all
vlib ${TP_PATH}/libs/lib_verilog
vmap lib_verilog ${TP_PATH}/libs/lib_verilog 

#compilation des fichiers
vlog +acc -work  lib_verilog ${TP_PATH}/rtl/*.sv
vlog +acc -work  lib_verilog ${TP_PATH}/bench/*.sv

#lancer la simulation du bench_riscv
    vsim -voptargs=+acc lib_verilog.bench2_riscv
    
    #ajout de rst et clk 
    add wave sim:/bench2_riscv/*
    #ajout du tableau instruction
    add wave -position insertpoint  \
    sim:/bench2_riscv/riscv1/imem1/tab_inst
    #ajout de la mémoire donnée
    add wave  \
    sim:/bench2_riscv/riscv1/mem1/mem
    #ajout des registres mémoires
    add wave -position insertpoint  \
    sim:/bench2_riscv/riscv1/regfile1/Registers
    #ajout de pc et next_instruction 
    add wave  \
    sim:/bench2_riscv/riscv1/imem1/inst_out
    add wave -position insertpoint  \
    sim:/bench2_riscv/riscv1/imem1/pc
    #rajouter tous les signaux des modules
    add wave -group imem sim:/bench2_riscv/riscv1/imem1/*
    add wave -group wb sim:/bench2_riscv/riscv1/wb1/*
    add wave -group regfile sim:/bench2_riscv/riscv1/regfile1/*
    add wave -group opti sim:/bench2_riscv/riscv1/opti1/*
    add wave -group imm_gen sim:/bench2_riscv/riscv1/imm_gen1/*
    add wave -group alu sim:/bench2_riscv/riscv1/alu1/*
    add wave -group mem sim:/bench2_riscv/riscv1/mem1/*
    add wave -group control_logic sim:/bench2_riscv/riscv1/control_logic1/*
    add wave -group wb sim:/bench2_riscv/riscv1/wb1/*
    #run
    run 500     

# #lancer simulation d'un autre module
#     vsim -voptargs=+acc lib_verilog.bench_regfile
#     add wave sim:/bench_regfile/regfile/*
#     add wave -position insertpoint  \
#     sim:/bench_regfile/regfile/Registers
#     run 500  
